apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umeshur/Shine-GitOps-Project.git
    targetRevision: main
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://C0FDDAA5A8C2E64BDF7FA631581EA58A.yl4.us-west-2.eks.amazonaws.com
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
